WEB/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('phonebook.urls')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phonebook/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .import views

app_name='phonebook'

urlpatterns=[
    path('login',auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LoginView.as_view(), name='logout'),
    path('signup',views.signup,name='signup'),
    path('',views.ContactListView.as_view(), name='contact-index'),
    path('add-contact',views.ContactcreateView.as_view(),name='add-contact'),
    path('<int:pk>/update-contact',views.ContactUpdateView.as_view(),name='update-contact'),
    path('<int:pk>/delete-contact',views.ContactDeleteVIEW.as_view(),name='delete-contact'),
]

contacts/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User


#Our models here.
class Contact(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=45)
    email=models.EmailField()
    telephone=models.CharField(max_length=15)
    relation=models.CharField(max_length=45)
    residence=models.CharField(max_length=45)
    cover=models.FileField()
    is_male=models.BooleanField(default=True)
    created=models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('phonebook:contact-index')

phonebook/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=45)
    email=models.EmailField()
    telephone=models.CharField(max_length=15)
    relation=models.CharField(max_length=45)
    residence=models.CharField(max_length=45)
    cover=models.FileField()
    is_male=models.BooleanField(default=True)
    created=models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('phonebook:contact-index')

phonebook/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model= User
        fields=['username','email','password']

contacts/views.py
from django.shortcuts import render

# Create your views here.

crud/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Contact
from .forms import UserForm
from django.contrib.auth import login, authenticate


# Create your views here.
class ContactListView(ListView):
    model = Contact
    context_object_name = 'contacts'


class ContactCreateView(CreateView):
    model = Contact
    fields = [
        'name', 'email', 'telephone',
        'relation', 'residence',
        'cover', 'is_male'
    ]

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ContactUpdateView(UpdateView):
    model = Contact
    fields = [
        'name', 'email', 'telephone',
        'relation', 'residence',
        'cover', 'is_male'
    ]


class ContactDeleteVIEW(DeleteView):
    model = Contact
    success_url = '/'


def signup(request):
    form = UserForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)

        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('phonebook:contact-index')
    return render(request, 'phonebook/signup.html', {'form': form})

phonebook/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView,UpdateView, DeleteView
from . models import Contact
from .forms import UserForm
from django.contrib.auth import login, authenticate

# Create your views here.
class ContactListView(ListView):
    model = Contact
    context_object_name = 'contacts'

class ContactcreateView(CreateView):
    model= Contact
    fields = [
        'name','email','telephone',
        'relation','residence',
        'cover','is_male'
    ]

class ContactUpdateView(UpdateView):
    model = Contact
    fields = [
        'name', 'email', 'telephone',
        'relation', 'residence',
        'cover', 'is_male'
    ]

class ContactDeleteVIEW(DeleteView):
    model = Contact
    success_url = '/'


def signup(request):
    form= UserForm(request.POST or None)
    
    if form.is_valid():
        username=form.cleaned_data['username']
        password=form.cleaned_data['password']
        user=form.save(commit=False)
        user.set_password(password)

        user.save()
        user=authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('phonebook:contact-index')
    return render(request, 'phonebook/signup.html',{'form':form})

phonebook/templates/phonebook/base.html
<html lang="en">
<head>
    <title>{%block title%}{%endblock%}</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">Contacts</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
    <ul class="navbar-nav navbar-right">
        <li class="nav-item">
            <a href="{%url 'phonebook:add-contact'%}"class="nav-link">Add contact</a>
        </li>
        <li class="nav-item">
            <a href=""class="nav-link">logout</a>
        </li>
    </ul>
</nav>
{% block content %}{% endblock %}
</body>
</html>

phonebook/templates/phonebook/contact_confirm_delete.html
{%extends 'phonebook/base.html'%}
{% block title %}Confirm delete{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-body my-1">
                <h3>Delete Contact {{object.name}}</h3>
                <hr>
                <p>Are you sure you want to Delete?</p>
                <form method="post">
                    {%csrf_token%}
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger">Yes,Delete</button>
                        <a href="{% url 'phonebook:contact-index'%}" class="btn btn-outline-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock%}

phonebook/templates/phonebook/contact_form.html
{% extends 'phonebook/base.html' %}
{% block titie%}{%if object%}Update{%else%} Add Contact{% endif %}{% endblock %}
{% load crispy_forms_tags %}

{%block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-body">
                <h4>{%if object%}Update {{object.name}}{%else%}Add Contact{%endif%}</h4>
                <hr>
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}


                 <div class="form-group">
                     <button type="submit" class="btn btn-info">{%if object %} Update {% else %} Submit {% endif %}</button>
                 </div>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock%}

phonebook/templates/phonebook/contact_list.html
{% extends 'phonebook/base.html' %}
{%block title%}Contacts{%endblock%}
{%block content%}
<div class="container">

    <div class="row">
        {% if contacts %}
            {% for contact in contacts %}
                <div class="col-sm-3">
                    <div class="card my-1"></div>
                    <div class="card">
                        <img src="{{contact.cover.url}}" class="img img-responsive" alt="" style="height:50px width:100px">
                        <div class="card-header" style="background-color:{%if contact.is_male%}blue;{%else%}red{%endif%}">
                            <i class="fas {%if contact.is_male%}fa-mars{%else%}fa-venus{%endif%}"></i>&nbsp; {{contact.name}}
                        </div>
                        <div class="card-body"  style="color:{%if contact.is_male%}blue;{%else%}red;{%endif%}">
                            <p><i class="fas fa-envelope"></i>&nbsp;{{contact.email}}</p>
                            <p><i class="fas fa-phone"></i>&nbsp;{{contact.telephone}}</p>
                            <p><i class="fas fa-user-circle"></i>&nbsp;{{contact.relation}}</p>
                            <p><i class="fas fa-globe"></i>&nbsp;{{contact.residence}} </p>
                            <a href="{%url 'phonebook:update-contact' contact.id %}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i></a>
                            <a href="{$url 'phonebook:delete-contact' contact.id%}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{%endblock%}

phonebook/templates/phonebook/signup.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{%load crispy_forms_tags%}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-body">
                <h3>Sign Up</h3>
                <form method="post" class="form-horizontal">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="form-group">
                        <button type="submit" class="btn btn-info">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>